### ISSUE TITLE
Run without KVM

### ISSUE THREAD

**Issue by DavHau** [Mic92/nixos-shell#17]
Would it be possible to run this without KVM support of the host system?
Many cloud environments do not enable hardware support for virtualization.

In this case one will get the error:
qemu-system-x86_64: CPU model 'host' requires KVM

Is qemu able to emulate the missing features somehow?

**Comment by Mic92** [comment]
nixos-shell is built around nixpkgs'qemu profile:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/qemu-vm.nix#L153

The kvm flag is hard-coded here:

https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/qemu-flags.nix#L25

**Comment by Mic92** [comment]
It might be possible to provide a second `-cpu` flag in QEMU_OPTS to override the first one. https://ahelpme.com/howto/qemu-full-virtualization-cpu-emulations-enable-disable-cpu-flags-instruction-sets/

**Comment by DavHau** [comment]
Thanks! I edited the qemu-flags.nix file from nixpkgs directly and set `-cpu Skylake-Client` and it worked.

How would one override QEMU_OPTS without touching nixpkgs directly?

**Comment by Mic92** [comment]
`$QEMU_OPTS` is simply read from environment variables. You can also set `virtualisation.qemu.options = "-hdc /dev/sdc";` with the same effect.

**Comment by DavHau** [comment]
```bash
export QEMU_OPTS="-cpu Skylake-Client"
nixos-shell
```
Works perfectly fine.
It's very very slow, since I guess the CPU is fully emulated. But it boots and is good enough to test a few simple services.

**Comment by DavHau** [comment]
Added it to the readme: https://github.com/Mic92/nixos-shell/pull/18
