### ISSUE TITLE
Add to nixpkgs?

### ISSUE THREAD

**Issue by dtzWill** [Mic92/nixos-shell#2]
Easy enough to install as-is but putting in nixpkgs would give it some visibility!

**Comment by Mic92** [comment]
I would like to see declarative `port-forwarding` first: https://github.com/Mic92/nixos-shell#port-forwarding
Then the API would be fixed.

**Comment by teto** [comment]
meanwhile it could reside in your nur repository https://github.com/Mic92/nur-packages/ (I couldn't find it) ?

**Comment by Mic92** [comment]
Its now part of nur-packages since https://github.com/Mic92/nur-packages/commit/cc40d087eedcb9b20d61557437839d052a4eef74

**Comment by Mic92** [comment]
Pull request: https://github.com/NixOS/nixpkgs/pull/85673
