### ISSUE TITLE
Q&A: How would I use nix-repl for config ?

### ISSUE THREAD

**Issue by 573** [Mic92/nixos-shell#23]
I would like to inspect the configuration settings (`config.`) in the spawned nixos-shell for what I did:

>nix repl '<nixpkgs/nixos>'

But it's only getting me back this:

>warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)

Is there another way I can say give me the equivalent /etc/configuration.nix ?

What I'd like to find out is if having `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` i. e. in my modified [vm.nix](https://github.com/Mic92/nixos-shell/blob/93df1dde693635f2573d584c001cc454dd983a1d/examples/vm.nix) does have any effect at all.

Or more general are any config values in the vm.nix file, i. e. smth like `users.users.builder = {..}` ?

**Comment by Mic92** [comment]
You would need to add a channel inside your vm. The alternative would be to `nix repl '<nixpkgs/nixos>' -I nixos-config=./vm.nix` on the host.

**Comment by 573** [comment]
Can I do smth about:
>nix-repl> config
error: The option `virtualisation.qemu' does not exist. Definition values:
>- In `/home/daniel/nixos-shell-2/examples/vm.nix':
    {
      networkingOptions = [
        "-net nic,netdev=user.0,model=virtio"
        "-netdev user,id=user.0,hostfwd=tcp::2222-:22"
      ];
    ...

**Comment by Mic92** [comment]
you could import `share/nixos-shell/nixos-shell.nix`.

**Comment by 573** [comment]
You mean as in:
>nix repl '<nixpkgs>' -I nixos-config=./examples/vm.nix -I nixos=share/nixos-shell/nixos-shell.nix

**Comment by 573** [comment]
Edited my above comment to narrow down the question scope.

**Comment by 573** [comment]
Importing like this doesn't work:

>$ cd ~/nixos-shell
$ nix repl '<nixpkgs/nixos>' -I nixos-config=./examples/vm.nix
Welcome to Nix version 2.3.8. Type :? for help.

Loading '<nixpkgs/nixos>'...
Added 6 variables.

nix-repl> (import ./share/nixos-shell/nixos-shell.nix)
«lambda @ /home/daniel/nixos-shell-2/share/nixos-shell/nixos-shell.nix:1:1»

nix-repl> config.virtualisation.qemu.networkingOptions
error: The option `virtualisation.qemu' does not exist. Definition values:
- In `/home/daniel/nixos-shell-2/examples/vm-forward.nix':
    {
      networkingOptions = [
        "-net nic,netdev=user.0,model=virtio"
        "-netdev user,id=user.0,hostfwd=tcp::2222-:22"
      ];
    ...

**Comment by Mic92** [comment]
You need to import in your configuration.

**Comment by Mic92** [comment]
But maybe doing it the other way around might be easier: 

```
$ QEMU_NIXOS_CONFIG=./vm.nix nix-build '<nixpkgs/nixos>' -A vm -k \
  -I "nixos-config=${script_dir}/../share/nixos-shell/nixos-shell.nix"
```

**Comment by Mic92** [comment]
also see https://github.com/Mic92/nixos-shell/blob/d84d32579026484e13d41547ff6ad73137cfcb42/bin/nixos-shell#L54

**Comment by 573** [comment]
Thanks so much!

> $ cd ~/nixos-shell
$ QEMU_NIXOS_CONFIG=/home/user/nixos-shell/examples/vm.nix nix repl '<nixpkgs/nixos>' -I "nixos-config=share/nixos-shell/nixos-shell.nix"

totally did what I needed it to do.
