### ISSUE TITLE
build error with qemu 5.2.0 

### ISSUE THREAD

**Issue by 573** [Mic92/nixos-shell#24]
See [comment in "qemu: 5.1.0 -> 5.2.0"](https://github.com/NixOS/nixpkgs/pull/106988#issuecomment-771552800).

To reproduce add `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` to examples/vm.nix and
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz make test
```

**Comment by Mic92** [comment]
Sorry this is a qemu build error from the looks of it and should be better discussed in nixpkgs itself.

**Comment by 573** [comment]
> 
> 
> Sorry this is a qemu build error from the looks of it and should be better discussed in nixpkgs itself.

[Done](https://github.com/NixOS/nixpkgs/issues/111651).
