### ISSUE TITLE
Q&A: How make nixos-shell working on patched nixpkgs set ?

### ISSUE THREAD

**Issue by 573** [Mic92/nixos-shell#26]
Say I had modified [default.nix](https://github.com/Mic92/nixos-shell/blob/master/default.nix) as in [this gist](https://gist.github.com/573/a35ed9fcfdf8e6d2ccc52443ff18fafb#file-default-nix)

Now a certain patch is applied but still nixos-shell I reckon https://github.com/Mic92/nixos-shell/blob/master/share/nixos-shell/nixos-shell.nix is still not using that package set. How would I modify that file or the other to achieve nixos-shell using my patched nixpkgs ?

**Comment by Mic92** [comment]
Does not work in with your approach.

```console
$ nixos-shell -I nixpkgs=/path/to/nixpkgs 
```

works however

**Comment by Mic92** [comment]
It would be a lot easier to just bring your two line fix upstream rather this complex machinery.

**Comment by 573** [comment]
See that as well now. 
Would weirdly involve setting NIX_PATH to the in the default.nix expression patched nixpkgs set's path so that can be picked up in the Makefile which would be kind of forward reference and impossible indeed.
Sry for the fuzz.
