### ISSUE TITLE
Question: Is space configurable via nixos-shell ?

### ISSUE THREAD

**Issue by 573** [Mic92/nixos-shell#30]
I am trying to spawn nixos-shell as a local builder for aarch64 packages on my x86_64 machine. Everything is working fine

```
NIX_BUILD_TOP=/tmp/build NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-build '<nixpkgs>' -A pkgsStatic.hledger --argstr system aarch64-linux --option sandbox false --builders 'ssh://nixos-shell aarch64-linux' -j0
```

But when I try to build more complex packages as in the example above I am getting

>error: preallocating file of 266966 bytes: No space left on device
error: writing to file: Broken pipe

Is there something I can tune via config here ? Thinking `examples/vm.nix`.

**Comment by Mic92** [comment]
Yes: https://github.com/NixOS/nixpkgs/blob/bf7940d1a8537bd1749bd39109851a73b112e4ef/nixos/modules/virtualisation/qemu-vm.nix#L292

Maybe you can add this to the README.

**Comment by 573** [comment]
Sure.

**Comment by 573** [comment]
@Mic92, may we reopen ?

Though having set `20 * 512` in vm.nix qemu monitor still tells me the device's size is 512 M:

>(qemu) info block -v
drive1 (#block174): /home/573/nixos-shell-2/nixos.qcow2 (qcow2)
    Attached to:      /machine/peripheral-anon/device[4]/virtio-backend
    Cache mode:       writeback
>
>Images:
image: /home/573/nixos-shell-2/nixos.qcow2
file format: qcow2
virtual size: 512 MiB (536870912 bytes)
disk size: 177 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false

Also attempting a remote build runs into a 
>copying path '/nix/store/pj1hc05cpbz3qgxc6m8a2ca92givqadb-ghc-8.10.2-binary' to 'ssh://nixos-shell'...
error: preallocating file of 83433 bytes: No space left on device
copying path '/nix/store/z4i4818n960nhd5r4vxd40a5bmq6nf2k-happy-1.20.0-data' to 'ssh://nixos-shell'...
error: preallocating file of 9927 bytes: No space left on device
error (ignored): unexpected end-of-file
error: writing to file: Broken pipe

**Comment by Mic92** [comment]
Have you deleted the local block device after changing the setting?

**Comment by Mic92** [comment]
I just tried the example configuration and it is indeed 10G:

```
╭─[root@nixos]─[~/git/nixos-shell]─[master*]
╰─ % lsblk
NAME MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0    2:0    1    4K  0 disk
sr0   11:0    1 1024M  0 rom
vda  253:0    0   10G  0 disk /
```

**Comment by 573** [comment]
You mean deleting `nixos.qcow2` ?
No, but I'll retry.

**Comment by 573** [comment]
That was it !
Again thanks !
> (qemu) info block -v
drive1 (#block165): /home/dkahlenberg/nixos-shell-2/nixos.qcow2 (qcow2)
    Attached to:      /machine/peripheral-anon/device[4]/virtio-backend
    Cache mode:       writeback
>
>Images:
image: /home/dkahlenberg/nixos-shell-2/nixos.qcow2
file format: qcow2
virtual size: 20 GiB (21474836480 bytes)
disk size: 15.5 MiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false

**Comment by 573** [comment]
IDK why my use case still doesn't work
When running `make test` creating a fresh `nixos.qcow2` I have another watching file's size. This is the state when `make test` finishes:
>Every 2.0s: du -h /home/dkahlenberg/nixos-shell-2/nixos.qcow2                       LCL: Tue Apr 20 13:19:38 2021
16M     /home/dkahlenberg/nixos-shell-2/nixos.qcow2

After running my remote build command which fails due to unknown reasons, lots of
>copying path '/nix/store/*********' to 'ssh://nixos-shell'...
error: preallocating file of 89248600 bytes: No space left on device

the state is:
>Every 2.0s: du -h /home/dkahlenberg/nixos-shell-2/nixos.qcow2                       LCL: Tue Apr 20 13:23:22 2021
22M     /home/dkahlenberg/nixos-shell-2/nixos.qcow2

Where would I have to create big random data file to reproduce ?

**Comment by Mic92** [comment]
Is your filesystem partition having the same size as the block device?

**Comment by Mic92** [comment]
Maybe we need some autoresize?

**Comment by 573** [comment]
I'll check.

Other finding:
>[root@nixos:~/nixos-shell-2]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         24M     0   24M   0% /dev
tmpfs           235M     0  235M   0% /dev/shm
tmpfs           118M  3.5M  114M   3% /run
tmpfs           235M  432K  234M   1% /run/wrappers
/dev/vda         20G   18M   19G   1% /
store           476G  401G   75G  85% /nix/.ro-store
tmpfs           235M  228M  6.3M  98% /nix/.rw-store
shared          476G  401G   75G  85% /tmp/shared
xchg            476G  401G   75G  85% /tmp/xchg
overlay         235M  228M  6.3M  98% /nix/store
home            476G  401G   75G  85% /home
nixprofile      476G  401G   75G  85% /nix/var/nix/profiles/per-user/dkahlenberg/profile
tmpfs            47M     0   47M   0% /run/user/0

**Comment by 573** [comment]
Hm
```
[root@nixos:~/nixos-shell-2]# sfdisk /dev/vda

Welcome to sfdisk (util-linux 2.36.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Checking that no-one is using this disk right now ... OK

The device contains 'ext4' signature and it will be removed by a write command. See sfdisk(8) man page and --wipe option for more details.

Disk /dev/vda: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

sfdisk is going to create a new 'dos' disk label.
Use 'label: <name>' before you define a first partition
to override the default.

Type 'help' to get more information.
```

**Comment by 573** [comment]
Doesn't surive a reboot.

**Comment by 573** [comment]
The error persists.

**Comment by Mic92** [comment]
Ah! Looks like changes to the nix store are stored in tmpfs rather than in the block device. You can disable that: 

https://github.com/NixOS/nixpkgs/blob/d9448c95c5d557d0b2e8bfe13e8865e4b1e3943f/nixos/modules/virtualisation/qemu-vm.nix#L398

`virtualisation.writableStoreUseTmpfs = false;`

**Comment by 573** [comment]
Thanks !
