### ISSUE TITLE
attribute 'nixos-shell' missing when using nur.repos.mic92.nixos-shell

### ISSUE THREAD

**Issue by shadowrylander** [Mic92/nixos-shell#33]
Hello!

Just as in the title; I can access the `nur` repository, but this particular package is not in your set. I also couldn't find it when searching through your `nur` repo; have you removed it?

Thank you kindly for the information!

**Comment by Mic92** [comment]
I removed it when the package also became available in nixpkgs stable as well.

**Comment by shadowrylander** [comment]
Got it; thanks!
