### ISSUE TITLE
[bug] nixos-shell does not find getty

### ISSUE THREAD

**Issue by AndersonTorres** [Mic92/nixos-shell#36]
Using the vm-efi.nix as example:

```
$> nixos-shell
warning: unknown setting 'experimental-features'
error: The option `services.getty' defined in `/nix/store/l2rg81cjbac3fvlir9k817qdw6z86kh8-nixos-shell-0.2.1/share/nixos-shell/nixos-shell.nix' does not exist.
(use '--show-trace' to show detailed location information)
```

**Comment by 573** [comment]
I get this when using an older `nixpkgs` as well (i. e. `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/4e2715934e2c995554c5d70fe4eea12716425480.tar.gz ...`), is removed with `nixpkgs-unstable`:

```sh
NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-shell --run "make test"
```

**Comment by Mic92** [comment]
Does this check not work? https://github.com/Mic92/nixos-shell/commit/78a93675bc49d9f094b2ec0d22e5e1074ca5a74a#diff-d3fbf970d03ec4e1f5d58857420e7b55f5083bf28e4eecd46c52577cae416499R100

**Comment by Mic92** [comment]
Or was it introduced after 20.09?

**Comment by 573** [comment]
I have the check in my clone so I'd suppose it does not ?

>$ git log | grep 78a9367
commit 78a93675bc49d9f094b2ec0d22e5e1074ca5a74a

**Comment by AndersonTorres** [comment]
nixos-version here is 21.11.20210709.45fc7d7 (Porcupine)

The error still persists.

**Comment by Mic92** [comment]
@AndersonTorres Are you sure your channel that is use for nixpkgs ist the same as the nixos version? I am pretty sure this option exists in 21.11

**Comment by AndersonTorres** [comment]
Well, now you have said, I have noticed my `nix-channel --list` is empty.

I am using a custom user environment trick, similar to the [lheckemann](
https://gist.github.com/lheckemann/402e61e8e53f136f239ecd8c17ab1deb)'s script.

**Comment by Mic92** [comment]
Hopefully no longer an issue for reasonable new NixOS configurations.
