### ISSUE TITLE
Getting setup-hook: cannot execute binary file error

### ISSUE THREAD

**Issue by 573** [Mic92/nixos-shell#38]
When trying to utilise nixos-shell as remote builder host for my WSL client I accidentally came up with this minimal example - also my issue (note that this command was executed inside the nixos-shell session):

>ssh nixos-shell
NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-shell -p nix-info --run "nix-info -m"
unpacking 'http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz'...
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/l31qzdd26g3rgn2a9h89sl7yjf71yim1-bash-interactive-4.4-p23-dev
copying path '/nix/store/l31qzdd26g3rgn2a9h89sl7yjf71yim1-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
/nix/store/qdf49mvm79r83n9c9s7pkmmjqwhrw8jv-stdenv-linux/setup: line 519: source: /nix/store/1xmid45vayj917km02cvkwq5054mz2ms-binutils-wrapper-2.35.1/nix-support/setup-hook: cannot execute binary file

The exact error I got when trying to build i. e. `pandoc` remotely as in:

```sh
NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-build -E '(with import <nixpkgs> { system = "x86_64-linux"; }; pkgs.haskell.packages.ghc884.ghcWithPackages (pkgs: [pkgs.pandoc]))' --option builders 'ssh://nixos-shell' # this got me the error as well, see below
NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-build -E '(with import <nixpkgs> {}; pkgs.haskell.packages.ghc884.ghcWithPackages (pkgs: [pkgs.pandoc]))' # while this built
```

Did I do something unusual here ?

The error log:

```log
copying path '/nix/store/6zinf42qdyfx528wgl428s9ljx80s86j-JuicyPixels-3.3.5.tar.gz' from 'https://cache.nixos.org'...
copying path '/nix/store/qk5hji9phm573cp51c97nhph4v6bwwmh-ghc-8.8.4-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/q427hhgznng6cg7510ir4cm41m32hjmn-hscolour-1.24.4' from 'https://cache.nixos.org'...
copying path '/nix/store/i8zrgs1k4w633cgn967ypfhimlpkmnj3-ghc-8.8.4' from 'https://cache.nixos.org'...
copying path '/nix/store/wsjhnhvpaw50jw7zm2zbf818iajr7kq5-primitive-0.7.1.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/fzwylip49bbs36534986di1n47jzclkl-zlib-0.6.2.3-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/fzsrycbcmm4kfhpsahnmv1pacrs2agh2-primitive-0.7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wpwfs183zgr5z258rpxaxxykfmh23lsr-vector-0.12.3.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/pi84scwxfxrif0qyz9vrlk6ff0jh58i7-zlib-0.6.2.3' from 'https://cache.nixos.org'...
copying path '/nix/store/faaa5szmazy4qasy2p99igwvzl2cadxy-vector-0.12.3.0' from 'https://cache.nixos.org'...
/nix/store/qdf49mvm79r83n9c9s7pkmmjqwhrw8jv-stdenv-linux/setup: line 519: source: /nix/store/1xmid45vayj917km02cvkwq5054mz2ms-binutils-wrapper-2.35.1/nix-support/setup-hook: cannot execute binary file
builder for '/nix/store/j1m8vd2qb047ims91gnkazlh54184dqx-JuicyPixels-3.3.5.drv' failed with exit code 126
```

**Comment by 573** [comment]
Is this related to the [setting](https://github.com/Mic92/nixos-shell/blame/90c9e3eff906fb578823b4f77deb025de808dbe3/README.md#L208)
```nix
{
nix.nixPath = [
  "nixpkgs=${pkgs.path}"
];
}
```

**Comment by Mic92** [comment]
NIX_PATH in the vm should not have any effect when doing remote building. There is no nix code evaluated inside the VM in this case. I would say your issues is maybe more related to what you are trying to build. Maybe check what is inside /nix/store/1xmid45vayj917km02cvkwq5054mz2ms-binutils-wrapper-2.35.1/nix-support/setup-hook inside the VM.

**Comment by 573** [comment]
@Mic92 good point.

I just can't explain why `setup-hook` is binary now in nixos-shell. When I probe on WSL

>$
head -c 16 /nix/store/1xmid45vayj917km02cvkwq5054mz2ms-binutils-wrapper-2.35.1/nix-support/setup-
hook | hexdump -C
00000000  23 20 53 69 6e 63 65 20  74 68 65 20 73 61 6d 65  |# Since the same|
00000010

vs. when I probe on host (nixos-shell)

>[root@nixos:~/nixos-shell-14-07-2021]#
head -c 16 /nix/store/1xmid45vayj917km02cvkwq5054mz2ms-binutils-wrapper-2.35.1/nix-support/setup
-hook | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010

**Comment by 573** [comment]
Without `virtualisation.writableStoreUseTmpfs = false;` in vm.nix I get

>\# NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.2, NixOS, 21.11pre302630.bfef28861df (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/store/52wjpq748sdxshkwjdaspixh3a47hpp9-nixexprs.tar.xz`

**Comment by 573** [comment]
My first attempt on garbage collecting (`nix-collect-garbage -d`) failed (had some disk space errors causing incomplete builds earlier) due to database inconsistencies, https://github.com/NixOS/nix/issues/2218#issuecomment-423853256 helped
```sh
sqlite3 /nix/var/nix/db/db.sqlite .dump | sed -e '/redmine/d' | sqlite3 /tmp/db.sqlite
mv /tmp/db.sqlite /nix/var/nix/db/db.sqlite
```
The garbage collection then succeeded and I was successful building `pandoc` on the remote host as well:
```sh
$ NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-build -E '(with import <nixpkgs> { system = "x86_64-linux"; }; pkgs.haskell.packages.ghc884.ghcWithPackages (pkgs: [pkgs.pandoc]))' --option builders 'ssh://nixos-shell'
```
