### ISSUE TITLE
Flake support

### ISSUE THREAD

**Issue by andrevmatos** [Mic92/nixos-shell#40]
How to get to a system built from a flake?
I'm currently using [flake-utils-plus](https://github.com/gytis-ivaskevicius/flake-utils-plus) to build and manage my main system, and it has a `hosts` options which allows to output multiple hosts as outputs, while sharing channels (inputs), overlays and modules between them.

It'd be great to be able to use `nixos-shell` to _boot_ one of these hosts directly, and have that documented. Not sure how to handle the custom `config.nixos-shell` on this context though. Sharing modules may make it easier to get into a `nixos-shell` without mounting home.

**Comment by Mic92** [comment]
This is not implemented. nixos-shell relies on many impure features. Just grep for `getEnv`: https://github.com/Mic92/nixos-shell/blob/master/share/nixos-shell/nixos-shell.nix

**Comment by srid** [comment]
This is done by https://github.com/Mic92/nixos-shell/pull/46
