### ISSUE TITLE
Error: Option virtualisation.memorySize is not of type positive integer

### ISSUE THREAD

**Issue by onny** [Mic92/nixos-shell#43]
Hey,
after a recent update I somehow get following error trying to use nixos-shell:
```
$ NIX_PATH=nixpkgs=/home/onny/projects/nixpkgs nixos-shell vm-opensnitchd.nix
error: A definition for option `virtualisation.memorySize' is not of type `positive integer, meaning >0'. Definition values:
- In `/nix/store/0q31g3syllx7335a3kjmw2rlsjnxn5nk-nixos-shell-0.2.1/share/nixos-shell/nixos-shell.nix': "500M"
(use '--show-trace' to show detailed location information)
```
Are there some changes in the background or is something wrong with my system settings?

Regards
Jonas

**Comment by Mic92** [comment]
Seems like this was changed here: https://github.com/NixOS/nixpkgs/commit/30f0faac22b6d8a6c6b308a0aa44ee672f2827eb#diff-5f468553a33ed484ce0a34ef2f404fb7f37bd981ba95fa5ec666bcbdaeb3d6d9
