### ISSUE TITLE
Force VM rebuild

### ISSUE THREAD

**Issue by onny** [Mic92/nixos-shell#47]
Hey,
I guess NixOS is caching somehow the state of a VM and only applies changes if you run it again.
How can I force a rebuild or delete the KVM images manually?

Regards
Jonas

**Comment by onny** [comment]
For clarification why I struggle with this issue: I'm using nixos-shell to test a module and it works great so far! The module / service is a web app which creates a Mysql database and uses it. To test it correctly, I want to start the module again with a fresh and clean database setup, without retaining the old entries.

**Comment by Mic92** [comment]
You can reset your virtual machine by deleting `nixos.qcow2` in the same directory.

**Comment by onny** [comment]
Oh nice thank you. Already tried that but somehow missed it. nixos-shell is so fast that I couldn't believe it ;)
