### ISSUE TITLE
Cannot override default net device

### ISSUE THREAD

**Issue by aidalgol** [Mic92/nixos-shell#51]
Trying to use the example config `vm-forward.nix` produces this error:
```console
qemu-kvm: -netdev user,id=user.0,hostfwd=tcp::2222-:22: Duplicate ID 'user.0' for netdev
```

This is on a nixpkgs-unstable system.  I can use `QEMU_NET_OPTS` as a workaround.

**Comment by fleaz** [comment]
I also just stumbled over this problem and got the same error message. To get a forwarded port into the VM one can just use
```
  virtualisation.forwardPorts = [
    { from = "host"; host.port = 222; guest.port = 22; }
  ];
```

**Comment by Mic92** [comment]
^ I believe this is the response.
