### ISSUE TITLE
How to use nixos-shell modules from a flake.nix file

### ISSUE THREAD

**Issue by nlewo** [Mic92/nixos-shell#54]
It would be nice to provide an example to illustrate how this could be used from a flake file, to build a VM using nixos-shell modules.

I currently have something such as:
```
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-21.11";
  outputs = { self, nixpkgs }: let
    pkgs = nixpkgs.legacyPackages."x86_64-linux";
    system = import (pkgs.path + /nixos) {
      system = "x86_64-linux";
      configuration = import ./configuration.nix;
    };
  in {
    defaultPackage.x86_64-linux = system.vm;
  };
}
```

How could i use nixos-shell modules to run this vm?

Note I would like to avoid relying on the nixos-shell script and use `nix build|run` directly instead.

**Comment by Mic92** [comment]
Implemented in https://github.com/Mic92/nixos-shell/pull/77/files

**Comment by nlewo** [comment]
Thank you!
