### ISSUE TITLE
warning message about programs.bash.enable

### ISSUE THREAD

**Issue by ryantm** [Mic92/nixos-shell#6]
When I run nixos-shell, I get this warning message:

```
trace: warning: The option definition `programs.bash.enable' in `/home/ryantm/.nix-profile/share/nixos-shell/nixos-shell.nix' no longer has any effect; please remove it.                                          
```

**Comment by Mic92** [comment]
cc @dermetfan 

we could drop the option if `SHELL == "bash"`:

https://github.com/Mic92/nixos-shell/blob/2d6b3b5074417b036eba8b44e6511fbfb49c07bd/share/nixos-shell/nixos-shell.nix#L74

**Comment by Mic92** [comment]
does this fix your problem? https://github.com/Mic92/nixos-shell/pull/7

**Comment by ryantm** [comment]
Yes, this fixes it.
