### ISSUE TITLE
Graphical log-in not working

### ISSUE THREAD

**Issue by Radvendii** [Mic92/nixos-shell#60]
I have this configuration
```
{ modulesPath, ... }: {
        # weird workaround https://github.com/NixOS/nixpkgs/issues/59219#issuecomment-774711048
        imports = [ (modulesPath + "/virtualisation/qemu-vm.nix") ];
        virtualisation.graphics = true;

        services.xserver = {
          enable = true;
          desktopManager.xfce.enable = true;
        };
};
```

And once I log in with `root` and empty password, the VM freezes. Sometimes I see the background of the login screen, and sometimes it fails to render entirely and I get my computers desktop background.

Same thing happens with `gnome` instead of `xfce`. I also tried upping `virtualisation.memory` to `1024`.

**Comment by alitibaliti** [comment]
As of 2/24/23 your snippet worked perfectly for me.

**Comment by Radvendii** [comment]
Maybe this got fixed. I haven't touched this in a while, so if nobody else is experiencing it I'll just close until / unless it comes up again.
