### ISSUE TITLE
Broken shell..cant install!

### ISSUE THREAD

**Issue by J7777785** [Mic92/nixos-shell#74]
So it's funny through this process I have found a four or so different ways to root my phone and it's been an amazing learning experience but my shell is broken right now and I was going to reboot my phone but I wanted to see if I could Rescue It with Nix... I didn't know if there was a way someone from the community could possibly help by secure SSH or FTP to me so that it installs because I can't complete any functions on my terminal

**Comment by J7777785** [comment]
I also know what files are fucked up and out of place that are causing all my problems but again I can't install them or move them because I can't get in

**Comment by Mic92** [comment]
I don't nixos-shell is the right tool to fix your broken phone.

**Comment by J7777785** [comment]
> I don't think nixos-shell is the right tool to fix your broken phone.

Yeah I'm suppose to start on gradel...but now I am interested in that nixos too.. not enough time in the day be getting distracted a lot learning a fuc ton in the last 2 days a lone. I'll do my best to share some documentation stumbled on one built into the Dec menue called angle too
