### ISSUE TITLE
Booting and specifiy different architecture

### ISSUE THREAD

**Issue by onny** [Mic92/nixos-shell#80]
Follow up to https://github.com/Mic92/nixos-shell/issues/39

Would be still nice to emulate a different architecture, such as aarch64, with nixos-shell :)

**Comment by onny** [comment]
As a workaround here's a flake.nix to boot up a aarch64 VM https://gist.github.com/lheckemann/63c52f2115346e6c9bbc6ecdfde9f43b?permalink_comment_id=5145608#gistcomment-5145608

**Comment by Mic92** [comment]
Fixed in https://github.com/Mic92/nixos-shell/pull/82

**Comment by onny** [comment]
Impressive, nice :D
